[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "symbro"
version = "0.1.0"
requires-python = ">=3.10"
license = { text = "Apache-2.0" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "numpy>=1.26",
    "pandas>=2.0",
    "gemmi>=0.7",
    "matplotlib>=3.7",
    "networkx>=3.0",
    "requests>=2.31",
    "PyYAML>=6.0",
    "rcsb-api>=1.7",
]

[tool.setuptools.packages.find]
where = ["src"]
